# Use the official Python image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy application files
COPY app.py requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000
EXPOSE 8000

# Run the application
CMD ["python", "app.py"]
